apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: personal
  description: 개인 프로젝트 소유 그룹
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: hwp
spec:
  memberOf: [personal]
